/*
-- Query: SELECT * FROM kallpa_sneakers.materia_prima
LIMIT 0, 400

-- Date: 2024-03-24 21:05
*/
INSERT INTO `` (`ID_Materia_Prima`,`Nombre`,`Descripcion`,`Rendimiemto_por_par`,`Precio_por_par`,`ID_Proveedor`,`Ultima_Modificacion`) VALUES (1,'capellada (P.U.)','Tela sintetica tambien conocida como cuero sintetico que es usada en el exterior de la calzado',4,1200.00,101,'2024-03-05');
INSERT INTO `` (`ID_Materia_Prima`,`Nombre`,`Descripcion`,`Rendimiemto_por_par`,`Precio_por_par`,`ID_Proveedor`,`Ultima_Modificacion`) VALUES (2,'Forro','Tela interior que se usa para la capa interna o revestimiento interior del calzado',12,538.46,101,'2024-03-05');
INSERT INTO `` (`ID_Materia_Prima`,`Nombre`,`Descripcion`,`Rendimiemto_por_par`,`Precio_por_par`,`ID_Proveedor`,`Ultima_Modificacion`) VALUES (3,'no tejido','Tela utilizada en el interior del calzado y que se produce sin la necesidad de tejer o hilar fibras',20,60.00,101,'2024-03-05');
INSERT INTO `` (`ID_Materia_Prima`,`Nombre`,`Descripcion`,`Rendimiemto_por_par`,`Precio_por_par`,`ID_Proveedor`,`Ultima_Modificacion`) VALUES (4,'etiquetas','Etiquetas que se cocen en la lengua o laterales del calzado',1,100.00,105,'2024-03-05');
INSERT INTO `` (`ID_Materia_Prima`,`Nombre`,`Descripcion`,`Rendimiemto_por_par`,`Precio_por_par`,`ID_Proveedor`,`Ultima_Modificacion`) VALUES (5,'hojalillos','Pequeños anillos metálicos utilizados en la confección del calzado donde van los cordones',1,30.00,104,'2024-03-05');
INSERT INTO `` (`ID_Materia_Prima`,`Nombre`,`Descripcion`,`Rendimiemto_por_par`,`Precio_por_par`,`ID_Proveedor`,`Ultima_Modificacion`) VALUES (6,'cordones','Tiras alargadas y flexibles que generalmente están hechas de diversos materiales',1,200.00,103,'2024-03-05');
INSERT INTO `` (`ID_Materia_Prima`,`Nombre`,`Descripcion`,`Rendimiemto_por_par`,`Precio_por_par`,`ID_Proveedor`,`Ultima_Modificacion`) VALUES (7,'plantilla vista','Plancha que es utilizada para hacer las plantillas en las zapatillas',30,160.00,101,'2024-03-05');
INSERT INTO `` (`ID_Materia_Prima`,`Nombre`,`Descripcion`,`Rendimiemto_por_par`,`Precio_por_par`,`ID_Proveedor`,`Ultima_Modificacion`) VALUES (8,'plantilla armado','Carton duro que se utiliza con la plantilla para reforzar la base de la zapatilla',30,133.33,102,'2024-03-05');
INSERT INTO `` (`ID_Materia_Prima`,`Nombre`,`Descripcion`,`Rendimiemto_por_par`,`Precio_por_par`,`ID_Proveedor`,`Ultima_Modificacion`) VALUES (9,'tela bostik','Tela dura que se flixibiliza al ser humedecida con pegamento para el armado con zapatillas.',30,150.00,102,'2024-03-05');
INSERT INTO `` (`ID_Materia_Prima`,`Nombre`,`Descripcion`,`Rendimiemto_por_par`,`Precio_por_par`,`ID_Proveedor`,`Ultima_Modificacion`) VALUES (10,'pegamento (p.v.c)','adhesivos específicamente diseñados para unir materiale como calzados',350,328.57,102,'2024-03-05');
INSERT INTO `` (`ID_Materia_Prima`,`Nombre`,`Descripcion`,`Rendimiemto_por_par`,`Precio_por_par`,`ID_Proveedor`,`Ultima_Modificacion`) VALUES (11,'neoprene','caucho sintético',250,396.00,102,'2024-03-05');
INSERT INTO `` (`ID_Materia_Prima`,`Nombre`,`Descripcion`,`Rendimiemto_por_par`,`Precio_por_par`,`ID_Proveedor`,`Ultima_Modificacion`) VALUES (12,'diluyentes','sustancias que se utilizan para reducir la viscosidad o espesor de ciertos productos químicos como adhesivo y facilitar el manejo del mismo',1,14.00,102,'2024-03-05');
INSERT INTO `` (`ID_Materia_Prima`,`Nombre`,`Descripcion`,`Rendimiemto_por_par`,`Precio_por_par`,`ID_Proveedor`,`Ultima_Modificacion`) VALUES (13,'base TR Kala','Bases de calzados T.R (Termoplástico Reforzado) de dama del articulo Kala',1,2700.00,107,'2024-03-05');
INSERT INTO `` (`ID_Materia_Prima`,`Nombre`,`Descripcion`,`Rendimiemto_por_par`,`Precio_por_par`,`ID_Proveedor`,`Ultima_Modificacion`) VALUES (14,'base P.V.C 5442','Base de calzado hecho con  policloruro de vinilo del articulo 5442',1,1500.00,107,'2024-03-05');
INSERT INTO `` (`ID_Materia_Prima`,`Nombre`,`Descripcion`,`Rendimiemto_por_par`,`Precio_por_par`,`ID_Proveedor`,`Ultima_Modificacion`) VALUES (15,'base expanso Jordan','Base calzado Jordan expanso blanca con base negra',1,1800.00,107,'2024-03-05');
INSERT INTO `` (`ID_Materia_Prima`,`Nombre`,`Descripcion`,`Rendimiemto_por_par`,`Precio_por_par`,`ID_Proveedor`,`Ultima_Modificacion`) VALUES (16,'base TR 5442','Bases de calzados T.R. (Termoplástico Reforzado) de hombre del articulo 5442',1,2500.00,107,'2024-03-05');
INSERT INTO `` (`ID_Materia_Prima`,`Nombre`,`Descripcion`,`Rendimiemto_por_par`,`Precio_por_par`,`ID_Proveedor`,`Ultima_Modificacion`) VALUES (17,'caja','Recipiente de carton donde van almacenadas los calzados',1,350.00,106,'2024-03-05');
INSERT INTO `` (`ID_Materia_Prima`,`Nombre`,`Descripcion`,`Rendimiemto_por_par`,`Precio_por_par`,`ID_Proveedor`,`Ultima_Modificacion`) VALUES (18,'papel sulfito','Papel finito que se usa en el emboltorio las zapatilla dentro de las cajas',1,14.00,106,'2024-03-05');
INSERT INTO `` (`ID_Materia_Prima`,`Nombre`,`Descripcion`,`Rendimiemto_por_par`,`Precio_por_par`,`ID_Proveedor`,`Ultima_Modificacion`) VALUES (19,'base lisa expanso','Base de calzado expanso articulo lisa blanca',1,1900.00,108,'2024-03-05');
INSERT INTO `` (`ID_Materia_Prima`,`Nombre`,`Descripcion`,`Rendimiemto_por_par`,`Precio_por_par`,`ID_Proveedor`,`Ultima_Modificacion`) VALUES (20,'lona tela','tela lona para zapatillas de diversos colores',1,1100.00,101,'2024-03-05');
INSERT INTO `` (`ID_Materia_Prima`,`Nombre`,`Descripcion`,`Rendimiemto_por_par`,`Precio_por_par`,`ID_Proveedor`,`Ultima_Modificacion`) VALUES (21,'microfibra','tela microfibra para azapatillas varios colores 1.5 diámetro',1,1150.00,101,'2024-03-05');
INSERT INTO `` (`ID_Materia_Prima`,`Nombre`,`Descripcion`,`Rendimiemto_por_par`,`Precio_por_par`,`ID_Proveedor`,`Ultima_Modificacion`) VALUES (22,'doble frontura','tela con microperforaciones de diferentes colores',1,1100.00,101,'2024-03-05');
